INSERT INTO CUSTOMER_TRANSACTION (CUSTOMER_ID, TRANSACTION_DATE, AMOUNT) VALUES (1, DATE_TRUNC('MONTH', LOCALTIMESTAMP - INTERVAL '1' MONTH), 120);
INSERT INTO CUSTOMER_TRANSACTION (CUSTOMER_ID, TRANSACTION_DATE, AMOUNT) VALUES (1, (DATE_TRUNC('MONTH', LOCALTIMESTAMP - INTERVAL '1' MONTH) + INTERVAL '14' DAY), 80);
INSERT INTO CUSTOMER_TRANSACTION (CUSTOMER_ID, TRANSACTION_DATE, AMOUNT) VALUES (1, FORMATDATETIME(CURRENT_TIMESTAMP, 'yyyy-MM-dd 00:00:00'), 60);
INSERT INTO CUSTOMER_TRANSACTION (CUSTOMER_ID, TRANSACTION_DATE, AMOUNT) VALUES (1, DATE_TRUNC('MONTH', LOCALTIMESTAMP - INTERVAL '2' MONTH), 150);
INSERT INTO CUSTOMER_TRANSACTION (CUSTOMER_ID, TRANSACTION_DATE, AMOUNT) VALUES (2, DATE_TRUNC('MONTH', LOCALTIMESTAMP - INTERVAL '1' MONTH), 90);
INSERT INTO CUSTOMER_TRANSACTION (CUSTOMER_ID, TRANSACTION_DATE, AMOUNT) VALUES (2, FORMATDATETIME(CURRENT_TIMESTAMP, 'yyyy-MM-dd 00:00:00'), 110);
INSERT INTO CUSTOMER_TRANSACTION (CUSTOMER_ID, TRANSACTION_DATE, AMOUNT) VALUES (2, DATE_TRUNC('MONTH', LOCALTIMESTAMP - INTERVAL '2' MONTH), 50);
INSERT INTO CUSTOMER_TRANSACTION (CUSTOMER_ID, TRANSACTION_DATE, AMOUNT) VALUES (2, '2024-12-15 00:00:00', 70);